import { makeBrokCodeSlug } from '@/lib/brokcode/project-store'

export type BrokCodeGithubExportFileInput = {
  path: string
  content: string
}

export type BrokCodeGithubExportFile = {
  path: string
  content: string
}

export type BrokCodeGithubExportSupportInput = {
  files: BrokCodeGithubExportFile[]
  exportPath?: string
  projectName?: string | null
  projectId?: string | null
  previewUrl?: string | null
  deploymentUrl?: string | null
  backend?: unknown
}

const MAX_EXPORT_FILES = 500
const MAX_EXPORT_FILE_BYTES = 1_000_000
const SECRET_FIELD_PATTERN = /(admin|secret|token|key|password|credential)/i

function normalizePathPart(part: string) {
  return part.trim().replace(/^\/+|\/+$/g, '')
}

export function sanitizeGithubExportPath(value: unknown) {
  if (typeof value !== 'string') return ''

  const path = value.split('/').map(normalizePathPart).filter(Boolean).join('/')

  if (!path) return ''
  const parts = path.split('/')
  if (
    parts.some(
      part =>
        part === '.' || part === '..' || part === '.git' || part.includes('\0')
    )
  ) {
    return ''
  }

  return path
}

function sanitizeProjectFilePath(value: string) {
  const path = value
    .split('/')
    .map(normalizePathPart)
    .filter(part => Boolean(part) && part !== '.')
    .join('/')

  if (!path) return null
  const parts = path.split('/')
  if (
    parts.some(
      part =>
        part === '..' ||
        part === '.git' ||
        part === 'node_modules' ||
        part.includes('\0')
    )
  ) {
    return null
  }

  return path
}

export function normalizeGithubExportFiles({
  files,
  exportPath = ''
}: {
  files: BrokCodeGithubExportFileInput[]
  exportPath?: string
}) {
  const root = sanitizeGithubExportPath(exportPath)
  const seen = new Set<string>()
  const normalized: BrokCodeGithubExportFile[] = []

  for (const file of files) {
    if (normalized.length >= MAX_EXPORT_FILES) break
    if (typeof file.content !== 'string') continue

    const relativePath = sanitizeProjectFilePath(file.path)
    if (!relativePath) continue

    const byteLength = new TextEncoder().encode(file.content).byteLength
    if (byteLength > MAX_EXPORT_FILE_BYTES) continue

    const path = root ? `${root}/${relativePath}` : relativePath
    if (seen.has(path)) continue

    seen.add(path)
    normalized.push({
      path,
      content: file.content
    })
  }

  return normalized.sort((a, b) => a.path.localeCompare(b.path))
}

function supportFilePath(exportPath: string | undefined, filePath: string) {
  const root = sanitizeGithubExportPath(exportPath)
  return root ? `${root}/${filePath}` : filePath
}

function hasExportFile(files: BrokCodeGithubExportFile[], path: string) {
  const normalizedPath = path.toLowerCase()
  return files.some(file => file.path.toLowerCase() === normalizedPath)
}

function redactExportMetadata(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(redactExportMetadata)
  }

  if (!value || typeof value !== 'object') {
    return value
  }

  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .filter(([key]) => key !== 'encryptedAdminKey')
      .map(([key, nestedValue]) => [
        key,
        SECRET_FIELD_PATTERN.test(key)
          ? nestedValue === null || nestedValue === false
            ? nestedValue
            : '[redacted]'
          : redactExportMetadata(nestedValue)
      ])
  )
}

function buildGithubExportReadme({
  projectName,
  projectId,
  previewUrl,
  deploymentUrl,
  files
}: BrokCodeGithubExportSupportInput) {
  const name = projectName?.trim() || 'BrokCode app'
  const hasPackage = files.some(file => /(^|\/)package\.json$/i.test(file.path))
  const hasStaticEntry = files.some(file =>
    /(^|\/)index\.html$/i.test(file.path)
  )
  const runSteps = hasPackage
    ? [
        '1. Install dependencies with `npm install` or your package manager.',
        '2. Start the app with the package `dev` script.',
        '3. Copy `.env.example` to `.env.local` and fill in backend values if needed.'
      ]
    : hasStaticEntry
      ? [
          '1. Serve the folder with any static file server.',
          '2. Open `index.html` in a browser.',
          '3. Copy `.env.example` before wiring live backend values.'
        ]
      : [
          '1. Review the exported source files.',
          '2. Add the runtime your project needs.',
          '3. Copy `.env.example` before wiring live backend values.'
        ]

  return [
    `# ${name}`,
    '',
    'Generated by BrokCode.',
    '',
    '## Project',
    '',
    projectId ? `- BrokCode project: \`${projectId}\`` : null,
    previewUrl ? `- Preview: ${previewUrl}` : null,
    deploymentUrl ? `- Deployment: ${deploymentUrl}` : null,
    '',
    '## Run Locally',
    '',
    ...runSteps,
    '',
    '## Deployment',
    '',
    'Use `DEPLOYMENT.md` for the deployment checklist and `insforge/config.json` for the non-secret backend handoff.',
    '',
    '## Security',
    '',
    'No provider secrets or raw BrokCode keys are included in this export. Keep all real keys in your deployment environment.'
  ]
    .filter((line): line is string => line !== null)
    .join('\n')
}

function buildGithubExportEnvExample() {
  return [
    '# Copy to .env.local or your deployment provider variables.',
    '# Never commit real provider, Brok, GitHub, Railway, or InsForge admin keys.',
    '',
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
    'NEXT_PUBLIC_INSFORGE_URL=',
    'NEXT_PUBLIC_INSFORGE_APP_KEY=',
    'BROK_API_KEY=',
    'INSFORGE_ADMIN_KEY='
  ].join('\n')
}

function buildGithubExportDeploymentGuide({
  projectName,
  previewUrl,
  deploymentUrl
}: BrokCodeGithubExportSupportInput) {
  const name = projectName?.trim() || 'BrokCode app'
  return [
    `# Deploy ${name}`,
    '',
    '## Checklist',
    '',
    '- Confirm the app runs locally.',
    '- Copy `.env.example` and fill secrets in the deployment platform, not in source control.',
    '- If this app uses InsForge, create or connect the matching backend resources before production traffic.',
    '- Run a production build before publishing.',
    '- Smoke-test the deployed URL after release.',
    '',
    '## BrokCode URLs',
    '',
    previewUrl ? `- Preview: ${previewUrl}` : '- Preview: not generated yet',
    deploymentUrl
      ? `- Deployment: ${deploymentUrl}`
      : '- Deployment: not published yet'
  ].join('\n')
}

function buildInsForgeConfig(backend: unknown) {
  const redacted = redactExportMetadata(backend)
  return JSON.stringify(
    {
      generatedBy: 'brokcode',
      backend: redacted ?? {
        provider: 'none',
        status: 'not_configured'
      },
      notes: [
        'This file intentionally excludes secrets.',
        'Use deployment environment variables for admin keys and provider tokens.'
      ]
    },
    null,
    2
  )
}

export function addGithubExportSupportFiles({
  files,
  exportPath,
  projectName,
  projectId,
  previewUrl,
  deploymentUrl,
  backend
}: BrokCodeGithubExportSupportInput) {
  const supportFiles: BrokCodeGithubExportFile[] = []
  const readmePath = supportFilePath(exportPath, 'README.md')
  const envPath = supportFilePath(exportPath, '.env.example')
  const deploymentPath = supportFilePath(exportPath, 'DEPLOYMENT.md')
  const backendPath = supportFilePath(exportPath, 'insforge/config.json')

  if (!hasExportFile(files, readmePath)) {
    supportFiles.push({
      path: readmePath,
      content: buildGithubExportReadme({
        files,
        projectName,
        projectId,
        previewUrl,
        deploymentUrl
      })
    })
  }

  if (!hasExportFile(files, envPath)) {
    supportFiles.push({ path: envPath, content: buildGithubExportEnvExample() })
  }

  if (!hasExportFile(files, deploymentPath)) {
    supportFiles.push({
      path: deploymentPath,
      content: buildGithubExportDeploymentGuide({
        files,
        projectName,
        previewUrl,
        deploymentUrl
      })
    })
  }

  if (!hasExportFile(files, backendPath)) {
    supportFiles.push({
      path: backendPath,
      content: buildInsForgeConfig(backend)
    })
  }

  return [...files, ...supportFiles].sort((a, b) =>
    a.path.localeCompare(b.path)
  )
}

export function buildGithubExportBranchName({
  projectName,
  projectId
}: {
  projectName?: string | null
  projectId?: string | null
}) {
  const slug = makeBrokCodeSlug(projectName || 'brokcode-project').slice(0, 40)
  const suffix = (projectId || Date.now().toString(36))
    .replace(/[^a-zA-Z0-9_-]/g, '')
    .slice(-8)

  return `brokcode/${slug}-${suffix || Date.now().toString(36)}`
}

export function buildGithubExportCommitMessage({
  projectId,
  versionId
}: {
  projectId?: string | null
  versionId?: string | null
}) {
  const parts = ['Export BrokCode project']
  if (projectId) parts.push(`project ${projectId}`)
  if (versionId) parts.push(`version ${versionId}`)
  return parts.join(' - ')
}

export function buildGithubExportPullRequestBody({
  body,
  projectId,
  versionId,
  exportPath,
  files
}: {
  body?: string
  projectId?: string | null
  versionId?: string | null
  exportPath?: string
  files: BrokCodeGithubExportFile[]
}) {
  const previewFiles = files.slice(0, 20).map(file => `- ${file.path}`)
  const hiddenCount = files.length - previewFiles.length
  const lines = [
    body?.trim() || 'Opened by Brok Code Cloud.',
    '',
    'BrokCode export:',
    projectId ? `- Project: ${projectId}` : null,
    versionId ? `- Version: ${versionId}` : null,
    `- Export path: ${exportPath || '/'}`,
    `- Files committed: ${files.length}`,
    '',
    'Files:',
    ...previewFiles,
    hiddenCount > 0 ? `- ...and ${hiddenCount} more` : null
  ].filter((line): line is string => Boolean(line))

  return lines.join('\n').slice(0, 65_000)
}
